### ISSUE TITLE
Incorrect permissions for pre/post-scripts

### ISSUE THREAD

**Issue by tronical** [stonemaster/github-actions-runner#2]
I'm trying to use the runner with the corresponding action, but the runner never ends up connecting to GitHub. I'm getting this in the `docker-compose logs`:

```
githubrunner     | Changing to user 'runner'.
githubrunner     | ./runner.sh: line 38: /home/runner/pre-script.sh: Permission denied
...
```

Permissions on the pre-script.sh seem to be set to 500, which I suppose won't work if `runner.sh` runs under a different user than the GH runner later?

Would you be open to a PR that uses 755 instead?

(I'm not 100% sure this is the exact reason why the runner doesn't come up for me, but I suspect it at least)

**Comment by stonemaster** [comment]
Could you try again using the latest images that was pushed just now (commit https://github.com/stonemaster/github-actions-runner/commit/dcc7ca357440988264fb672bf6666aad2620e29a). I tried some stuff regarding docker-in-docker builds and it might very well be that those two commits broke stuff :-|

**Comment by tronical** [comment]
Sure! Do you know if there is an easy way to do that from the action?

**Comment by tronical** [comment]
Meanwhile, I’ve been able to get the runner working despite this error - I also had a token permission problem. Feel free to close this issue :)

**Comment by stonemaster** [comment]
The build is automatically uploaded with each commit 😀 just for the record: how did you circumvent the problem? Or is there anything that could be handled better inside the container?

**Comment by tronical** [comment]
Oh Great :). It's possible that I was chasing a ghost. I saw that an earlier step had also failed (runner registration api call), perhaps that cascaded into not switching to the correct runner user.

Now all is running smooth - great work with this action. (Only caveat for me is right now that the base image from GH is using that old Ubuntu version...)
